<a href="https://colab.research.google.com/github/keshav340/python-library/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
numbers =np.array([45,78,56,456])
type(numbers)
numbers

array([ 45,  78,  56, 456])

In [6]:
np.array([[45,68,79], [78,659,782]])

array([[ 45,  68,  79],
       [ 78, 659, 782]])

In [7]:
np.array([2,4,6,8,10,12,14,16,18,20])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
np.array([[2,4,6,8,10],[1,3,5,7,9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [9]:
#array attribute
integers = np.array([[2,4,6,8,10],[1,3,5,7,9]])
float = np.array([0.1, 0.2, 0.3, 0.9, 0.7 ,0.5])

In [10]:
float

array([0.1, 0.2, 0.3, 0.9, 0.7, 0.5])

In [11]:
float.dtype

dtype('float64')

In [13]:
float.ndim

1

In [14]:
float.shape

(6,)

In [15]:
float.size

6

In [16]:
float.itemsize

8

In [20]:
for i in integers.flat:
  print(i, end='')

24681013579

In [22]:
#create array   wih specfiic value
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones((6,9), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [24]:
np.full((3,5),45)

array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]])

In [25]:
import numpy as np
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [27]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [29]:
np.arange(5,10, 2)


array([5, 7, 9])

In [31]:
np.linspace(1,7,num=10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [32]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
np.arange(1,100001).reshape(4,25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [36]:
#array operator
numbers =np.arange(1,7)

In [38]:
numbers

array([1, 2, 3, 4, 5, 6])

In [39]:
numbers*2

array([ 2,  4,  6,  8, 10, 12])

In [40]:
numbers**3

array([  1,   8,  27,  64, 125, 216])

In [41]:
numbers +=10

In [42]:
numbers

array([11, 12, 13, 14, 15, 16])

In [46]:
numbers2 = np.linspace(1,6, 6)

In [47]:
numbers2

array([1., 2., 3., 4., 5., 6.])

In [48]:

numbers * numbers2

array([11., 24., 39., 56., 75., 96.])

In [51]:
numbers >= 13

array([False, False,  True,  True,  True,  True])

In [52]:
numbers <= numbers2

array([False, False, False, False, False, False])